[package]
name = "fungai"
version = "0.1.0"
edition = "2021"
authors = ["Ardu"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "your_library_name"
path = "src/lib.rs"

[dependencies]
ndarray = "0.15.6"
rand = "0.8.5"
